# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MeshCentral add-on
version: "0.1.0"
slug: meshcentral
description: MeshCentral add-on
url: "https://github.com/amasolov/homeassistant-addon-meshcentral/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "docker.io/amasolov/{arch}-addon-meshcentral"
